import { render } from "preact";
import { useEffect, useState } from "preact/hooks";
import { api, formatDate, formatNumber } from "./api";
import { AppShell, Button, Empty, Icon, Logo, PageHeader, Panel, Stat, type View } from "./components";
import "./styles.css";

type Account = { id: string; name: string; enabled: boolean; accountId: string; email?: string; principalId: string; cooldownUntil: number; failureCount: number; lastStatus?: number; usage?: { primary?: UsageWindow; secondary?: UsageWindow; creditsBalance?: number; capturedAt: number; error?: string } };
type UsageWindow = { remainingPercent: number; windowMinutes: number; resetsAt: number };
type ProxyKey = { id: string; name: string; prefix: string; createdAt?: number; revokedAt?: number; recoverable?: boolean };
type Settings = { selectionStrategy: string; maxAccountAttempts: number; tokenExpiryBufferMinutes: number; rateLimitCooldownSeconds: number; authCooldownSeconds: number; serverErrorCooldownSeconds: number };
type Model = { id: string; name?: string; supported_endpoints?: string[]; capabilities?: { limits?: { max_context_window_tokens?: number; max_output_tokens?: number }; supports?: Record<string, boolean> } };
type Stats = { totals: Record<string, number>; models: Array<Record<string, any>>; recent: Array<Record<string, any>> };
type Toast = { title: string; message: string; error?: boolean };
type Dialog = "import" | "device" | "browser" | "key" | null;

const validViews = new Set(["home", "accounts", "keys", "models", "usage", "settings"]);
function hashView(): View { const value = location.hash.slice(1); return (validViews.has(value) ? value : "home") as View; }

function App() {
  const [view, setView] = useState<View>(hashView());
  const [theme, setThemeState] = useState(document.documentElement.dataset.theme || "system");
  const [authenticated, setAuthenticated] = useState<boolean | null>(null);
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [keys, setKeys] = useState<ProxyKey[]>([]);
  const [settings, setSettings] = useState<Settings | null>(null);
  const [models, setModels] = useState<Model[] | null>(null);
  const [stats, setStats] = useState<Stats | null>(null);
  const [dialog, setDialog] = useState<Dialog>(null);
  const [toast, setToast] = useState<Toast | null>(null);
  const notify = (title: string, message: string, error = false) => setToast({ title, message, error });
  const loadCore = async () => { const [a, k, s, r] = await Promise.all([api<{ accounts: Account[] }>("/admin/api/accounts"), api<{ keys: ProxyKey[] }>("/admin/api/proxy-keys"), api<{ settings: Settings }>("/admin/api/settings"), api<Stats>("/admin/api/request-stats")]); setAccounts(a.accounts || []); setKeys(k.keys || []); setSettings(s.settings); setStats(r); };
  useEffect(() => { loadCore().then(() => setAuthenticated(true)).catch(() => setAuthenticated(false)); }, []);
  useEffect(() => { const update = () => setView(hashView()); addEventListener("hashchange", update); return () => removeEventListener("hashchange", update); }, []);
  useEffect(() => { if (view === "models" && models === null) loadModels(); }, [view]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(null), 4200); return () => clearTimeout(timer); }, [toast]);
  const setTheme = (value: string) => { document.documentElement.dataset.theme = value; localStorage.setItem("codex-theme", value); setThemeState(value); };
  const loadModels = async (refresh = false) => { try { const data = await api<{ data: Model[] }>(`/admin/api/models${refresh ? "?refresh=1" : ""}`); setModels(data.data || []); if (refresh) notify("模型已刷新", `已读取 ${data.data?.length || 0} 个可用模型。`); } catch (error) { setModels([]); notify("模型载入失败", message(error), true); } };
  const refreshUsage = async () => { try { const data = await api<{ accounts: Account[] }>("/admin/api/accounts/usage", { method: "POST", body: "{}" }); setAccounts(data.accounts || []); notify("额度已刷新", "已更新所有启用账户的剩余额度。"); } catch (error) { notify("刷新失败", message(error), true); } };
  const logout = async () => { await api("/admin/api/session", { method: "DELETE" }).catch(() => {}); location.reload(); };
  if (authenticated === null) return <div class="loading">正在载入账户池...</div>;
  if (!authenticated) return <><Login onSuccess={async () => { await loadCore(); setAuthenticated(true); }} notify={notify} />{toast && <ToastMessage toast={toast} />}</>;
  return <><AppShell view={view} theme={theme} onTheme={setTheme} onLogout={logout}>{view === "home" && <Home accounts={accounts} keys={keys} models={models} stats={stats} settings={settings} />}{view === "accounts" && <Accounts accounts={accounts} setAccounts={setAccounts} open={setDialog} refresh={refreshUsage} notify={notify} />}{view === "keys" && <Keys keys={keys} setKeys={setKeys} open={setDialog} notify={notify} />}{view === "models" && <Models models={models} refresh={() => loadModels(true)} />}{view === "usage" && <Usage stats={stats} refresh={async () => { try { const data = await api<Stats>("/admin/api/request-stats"); setStats(data); notify("统计已刷新", "已更新请求与 Token 汇总。"); } catch (error) { notify("刷新失败", message(error), true); } }} />}{view === "settings" && settings && <SettingsPage settings={settings} setSettings={setSettings} notify={notify} />}</AppShell><Dialogs dialog={dialog} close={() => setDialog(null)} reloadAccounts={async () => { const data = await api<{ accounts: Account[] }>("/admin/api/accounts"); setAccounts(data.accounts || []); }} reloadKeys={async () => { const data = await api<{ keys: ProxyKey[] }>("/admin/api/proxy-keys"); setKeys(data.keys || []); }} notify={notify} />{toast && <ToastMessage toast={toast} />}</>;
}

function ToastMessage({ toast }: { toast: Toast }) { return <div class={`toast ${toast.error ? "error" : ""}`}><strong>{toast.title}</strong><span>{toast.message}</span></div>; }

function Login({ onSuccess, notify }: { onSuccess: () => Promise<void>; notify: Function }) { const [key, setKey] = useState(""); const submit = async (event: Event) => { event.preventDefault(); try { await api("/admin/api/session", { method: "POST", body: JSON.stringify({ key }) }); await onSuccess(); } catch (error) { notify("无法登录", message(error), true); } }; return <main class="login"><form class="login-card" onSubmit={submit}><Logo large /><h1>管理员登录</h1><p>此备用入口用于本地开发。生产环境请通过 Cloudflare Access 登录。</p><label>管理员 API 密钥<input type="password" value={key} onInput={(event) => setKey(event.currentTarget.value)} autoComplete="current-password" /></label><Button tone="primary" type="submit">登录</Button></form></main>; }

function Home({ accounts, keys, models, stats, settings }: any) { const healthy = accounts.filter((a: Account) => a.enabled && a.cooldownUntil <= Date.now()).length; const cards: Array<[View, string, string, string]> = [["accounts", "账户池", `${accounts.length} 个账户 · ${healthy} 个可用`, "导入、启用或停用 OAuth 账户，查看健康状态与额度。"], ["keys", "密钥", `${keys.filter((k: ProxyKey) => !k.revokedAt).length} 把有效密钥`, "为客户端创建、查看或注销独立 API 密钥。"], ["models", "模型", models ? `${models.length} 个可用模型` : "进入后读取实时目录", "查看健康账户可使用的模型与能力。"], ["usage", "请求统计", `${formatNumber(stats?.totals?.requests)} 次请求`, "查看 Token 消耗、状态与最近调用。"], ["settings", "运行设置", settings?.selectionStrategy === "least_failures" ? "优先健康账户" : "顺序轮询", "配置故障转移、刷新与冷却策略。"]]; return <><PageHeader eyebrow="Cloudflare Durable Objects" title="运行概览" description="账户、密钥、模型、请求统计和运行设置集中在一个工作区。" /><div class="stats"><Stat label="账户总数" value={accounts.length} /><Stat label="可用账户" value={healthy} /><Stat label="冷却或停用" value={accounts.length - healthy} /></div><div class="card-grid">{cards.map(([id, title, value, text]) => <Panel class="home-card"><h3>{title}</h3><strong class="card-value">{value}</strong><p>{text}</p><a class="button" href={`#${id}`}>打开{title}</a></Panel>)}</div></>; }

function Accounts({ accounts, setAccounts, open, refresh, notify }: any) { const toggle = async (account: Account) => { try { await api(`/admin/api/accounts/${encodeURIComponent(account.id)}`, { method: "PATCH", body: JSON.stringify({ enabled: !account.enabled }) }); setAccounts(accounts.map((a: Account) => a.id === account.id ? { ...a, enabled: !a.enabled } : a)); } catch (error) { notify("操作失败", message(error), true); } }; const remove = async (account: Account) => { if (!confirm(`确定删除“${account.name}”？此操作无法撤销。`)) return; try { await api(`/admin/api/accounts/${encodeURIComponent(account.id)}`, { method: "DELETE" }); setAccounts(accounts.filter((a: Account) => a.id !== account.id)); } catch (error) { notify("删除失败", message(error), true); } }; const loginActions = <><Button onClick={() => open("browser")}>复制链接登录</Button><Button tone="primary" onClick={() => open("device")}>使用 ChatGPT 登录</Button></>; return <><PageHeader eyebrow="Account routing" title="账户池" description="管理参与轮询和故障转移的 Codex OAuth 账户。" actions={<><Button onClick={refresh}>刷新额度</Button><Button onClick={() => open("import")}>手动导入</Button>{loginActions}</>} /><Panel title="账户与额度" subtitle="令牌和额度查询均只在服务端完成。"><div class="list">{accounts.length ? accounts.map((account: Account) => <article class="account-row"><div class="identity"><span class="avatar">{(account.email || account.name || "A")[0].toUpperCase()}</span><div><h3>{account.name}</h3><p>{account.email || account.principalId}</p><small>Workspace · {account.accountId}</small></div></div><Quota label="主额度" window={account.usage?.primary} error={account.usage?.error} /><Quota label="次额度" window={account.usage?.secondary} error={account.usage?.error} /><div><span class={`status ${account.enabled && account.cooldownUntil <= Date.now() ? "healthy" : "disabled"}`}>{!account.enabled ? "已停用" : account.cooldownUntil > Date.now() ? "冷却中" : "可用"}</span><small>失败 {account.failureCount}{account.lastStatus ? ` · HTTP ${account.lastStatus}` : ""}</small></div><div class="row-actions"><Button onClick={() => toggle(account)}>{account.enabled ? "停用" : "启用"}</Button><Button tone="danger" onClick={() => remove(account)}>删除</Button></div></article>) : <Empty title="还没有账户" text="登录 ChatGPT 自动添加账户，或手动导入现有凭据。" actions={<><Button onClick={() => open("import")}>手动导入</Button>{loginActions}</>} />}</div></Panel></>; }
function Quota({ label, window, error }: { label: string; window?: UsageWindow; error?: string }) { if (error || !window) return <div class="quota"><small>{label}</small><span>{error ? "暂时无法获取" : "尚未刷新"}</span></div>; const value = Math.max(0, Math.min(100, Number(window.remainingPercent) || 0)); return <div class="quota"><small>{label}</small><strong>{value.toFixed(0)}%</strong><div class="quota-track"><i style={{ width: `${value}%` }} /></div><span>重置 {formatDate(window.resetsAt * 1000)}</span></div>; }

function Keys({ keys, setKeys, open, notify }: any) { const [revealed, setRevealed] = useState<Record<string, string>>({}); const reveal = async (key: ProxyKey) => { if (revealed[key.id]) { const copy = { ...revealed }; delete copy[key.id]; setRevealed(copy); return; } try { const data = await api<{ key: string }>(`/admin/api/proxy-keys/${encodeURIComponent(key.id)}/reveal`); setRevealed({ ...revealed, [key.id]: data.key }); } catch (error) { notify("查看失败", message(error), true); } }; const revoke = async (key: ProxyKey) => { if (!confirm(`确定注销“${key.name}”？`)) return; try { await api(`/admin/api/proxy-keys/${encodeURIComponent(key.id)}`, { method: "DELETE" }); setKeys(keys.filter((item: ProxyKey) => item.id !== key.id)); } catch (error) { notify("注销失败", message(error), true); } }; return <><PageHeader eyebrow="Client authentication" title="密钥" description="为不同客户端创建、查看或注销独立 API 密钥。" actions={<Button tone="primary" onClick={() => open("key")}>新建密钥</Button>} /><Panel title="客户端 API 密钥" subtitle="可恢复内容使用 AES-GCM 加密保存；请求鉴权仅使用哈希。">{keys.length ? <div class="list">{keys.map((key: ProxyKey) => <article class="key-row"><div><h3>{key.name} <span class={`status ${key.revokedAt ? "disabled" : "healthy"}`}>{key.revokedAt ? "已注销" : key.recoverable ? "有效" : "仅哈希"}</span></h3><code>{key.prefix}</code></div><span>{key.createdAt ? formatDate(key.createdAt) : "升级前创建"}</span><div class="row-actions">{!key.revokedAt && key.recoverable && <Button onClick={() => reveal(key)}>{revealed[key.id] ? "隐藏" : "查看"}</Button>}{!key.revokedAt && <Button tone="danger" onClick={() => revoke(key)}>注销</Button>}</div>{revealed[key.id] && <div class="revealed"><code>{revealed[key.id]}</code><Button onClick={() => navigator.clipboard.writeText(revealed[key.id])}>复制</Button></div>}</article>)}</div> : <Empty title="还没有客户端密钥" text="为每个设备或服务创建一把独立密钥。" actions={<Button tone="primary" onClick={() => open("key")}>新建密钥</Button>} />}</Panel></>; }

function Models({ models, refresh }: { models: Model[] | null; refresh: () => void }) { return <><PageHeader eyebrow="Live model catalog" title="可用模型" description="通过当前健康账户实时读取模型、上下文限制与支持能力。" actions={<Button onClick={refresh}>刷新目录</Button>} /><Panel title="模型目录" subtitle={models === null ? "正在载入..." : `当前账户池可用 ${models.length} 个模型。`}>{models?.length ? <div class="model-grid">{models.map((model) => <article class="model-card"><div><h3>{model.name || model.id}</h3><code>{model.id}</code></div><span class="status healthy">可用</span><div class="badges"><span>{tokens(model.capabilities?.limits?.max_context_window_tokens)} 上下文</span><span>{tokens(model.capabilities?.limits?.max_output_tokens)} 输出</span>{Object.entries(model.capabilities?.supports || {}).filter(([, enabled]) => enabled).map(([name]) => <span>{name}</span>)}</div></article>)}</div> : <Empty title={models === null ? "正在载入模型" : "没有可用模型"} text="请先添加并启用至少一个账户。" />}</Panel></>; }

function Usage({ stats, refresh }: { stats: Stats | null; refresh: () => void }) { const totals = stats?.totals || {}; return <><PageHeader eyebrow="Request analytics" title="请求统计" description="按模型查看请求量、Token 消耗和最近调用，不保存提示词或响应正文。" actions={<Button onClick={refresh}>刷新统计</Button>} /><div class="stats four"><Stat label="请求总数" value={formatNumber(totals.requests)} /><Stat label="Input Tokens" value={formatNumber(totals.inputTokens)} /><Stat label="Output Tokens" value={formatNumber(totals.outputTokens)} /><Stat label="Total Tokens" value={formatNumber(totals.totalTokens)} /></div><Panel title="按模型汇总"><Table headers={["模型", "请求", "成功", "Input", "Output", "Total", "最近请求"]} rows={(stats?.models || []).map((item) => [item.model, formatNumber(item.requests), formatNumber(item.successfulRequests), formatNumber(item.inputTokens), formatNumber(item.outputTokens), formatNumber(item.totalTokens), formatDate(item.lastRequestedAt)])} /></Panel><Panel title="最近请求" subtitle="最多保留最近 200 条元数据记录。"><Table headers={["时间", "模型", "接口", "状态", "耗时", "Token", "模式"]} rows={(stats?.recent || []).map((item) => [formatDate(item.createdAt), item.model, item.endpoint, item.status, `${formatNumber(item.durationMs)} ms`, item.usage?.available ? formatNumber(item.usage.totalTokens) : "—", item.streaming ? "流式" : "普通"])} /></Panel></>; }
function Table({ headers, rows }: { headers: string[]; rows: any[][] }) { return <div class="table-wrap"><table><thead><tr>{headers.map((header) => <th>{header}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row) => <tr>{row.map((cell) => <td>{cell}</td>)}</tr>) : <tr><td colSpan={headers.length}>尚无记录</td></tr>}</tbody></table></div>; }

const settingRows: Array<[keyof Settings, string, string, number?, number?]> = [["maxAccountAttempts", "最大尝试次数", "单个请求最多尝试多少个账户。", 1, 10], ["tokenExpiryBufferMinutes", "Token 提前刷新", "到期前多少分钟刷新 OAuth Token。", 5, 120], ["rateLimitCooldownSeconds", "429 冷却时间", "上游没有 Retry-After 时使用的秒数。", 5, 900], ["authCooldownSeconds", "认证失败冷却", "收到认证失败或刷新失败后的秒数。", 30, 1800], ["serverErrorCooldownSeconds", "服务错误冷却", "收到 5xx 后的基础秒数。", 5, 300]];
function SettingsPage({ settings, setSettings, notify }: { settings: Settings; setSettings: (s: Settings) => void; notify: Function }) { const [draft, setDraft] = useState(settings); useEffect(() => setDraft(settings), [settings]); const update = (key: keyof Settings, value: string | number) => setDraft({ ...draft, [key]: value }); const save = async () => { try { const data = await api<{ settings: Settings }>("/admin/api/settings", { method: "PATCH", body: JSON.stringify(draft) }); setSettings(data.settings); notify("设置已保存", "新的路由与冷却策略已立即生效。"); } catch (error) { notify("保存失败", message(error), true); } }; return <><PageHeader eyebrow="Runtime configuration" title="其他设置" description="修改账户选择、故障转移、刷新和冷却行为。" actions={<Button tone="primary" onClick={save}>保存更改</Button>} /><Panel title="运行设置" subtitle="保存后立即对新请求生效，并持久化到 Durable Object。"><div class="settings"><label><span><strong>账户选择策略</strong><small>顺序轮询强调均衡；优先健康账户选择失败次数更少的账户。</small></span><select value={draft.selectionStrategy} onChange={(e) => update("selectionStrategy", e.currentTarget.value)}><option value="round_robin">顺序轮询</option><option value="least_failures">优先健康账户</option></select></label>{settingRows.map(([key, title, text, min, max]) => <label><span><strong>{title}</strong><small>{text}</small></span><input type="number" min={min} max={max} value={draft[key]} onInput={(e) => update(key, Number(e.currentTarget.value))} /></label>)}</div></Panel></>; }

function Dialogs({ dialog, close, reloadAccounts, reloadKeys, notify }: any) { if (!dialog) return null; if (dialog === "import") return <ImportDialog close={close} reload={reloadAccounts} notify={notify} />; if (dialog === "key") return <KeyDialog close={close} reload={reloadKeys} notify={notify} />; return <OAuthDialog mode={dialog} close={close} reload={reloadAccounts} notify={notify} />; }
function Modal({ title, subtitle, close, children, footer }: any) { return <div class="veil" onMouseDown={(e) => e.currentTarget === e.target && close()}><section class="dialog" role="dialog" aria-modal="true"><header><div><h2>{title}</h2><p>{subtitle}</p></div><Button class="icon-button" onClick={close} aria-label="关闭"><Icon name="close" /></Button></header><div class="dialog-body">{children}</div>{footer && <footer>{footer}</footer>}</section></div>; }
function ImportDialog({ close, reload, notify }: any) { const [name, setName] = useState(""); const [payload, setPayload] = useState(""); const submit = async () => { try { const body = JSON.parse(payload); if (name.trim()) body.name = name.trim(); await api("/admin/api/accounts", { method: "POST", body: JSON.stringify(body) }); await reload(); close(); notify("账户已导入", "已安全保存并加入轮询。"); } catch (error) { notify("导入失败", error instanceof SyntaxError ? "凭据不是有效的 JSON。" : message(error), true); } }; return <Modal title="导入 Codex 账户" subtitle="令牌不会由管理 API 返回。" close={close} footer={<><Button onClick={close}>取消</Button><Button tone="primary" onClick={submit}>安全导入</Button></>}><label>显示名称<input value={name} onInput={(e) => setName(e.currentTarget.value)} /></label><label>凭据 JSON<textarea value={payload} onInput={(e) => setPayload(e.currentTarget.value)} placeholder={'{"tokens":{"access_token":"...","refresh_token":"..."}}'} /></label></Modal>; }
function KeyDialog({ close, reload, notify }: any) { const [name, setName] = useState(""); const [key, setKey] = useState(""); const submit = async () => { if (!name.trim()) return notify("请输入名称", "密钥名称用于区分客户端。", true); try { const data = await api<{ key: string }>("/admin/api/proxy-keys", { method: "POST", body: JSON.stringify({ name: name.trim() }) }); setKey(data.key); await reload(); } catch (error) { notify("生成失败", message(error), true); } }; return <Modal title="新建客户端密钥" subtitle="不同设备或服务建议使用不同密钥。" close={close} footer={<>{key ? <Button tone="primary" onClick={() => navigator.clipboard.writeText(key)}>复制密钥</Button> : <Button tone="primary" onClick={submit}>生成密钥</Button>}</>}><label>密钥名称<input value={name} onInput={(e) => setName(e.currentTarget.value)} /></label>{key && <div class="revealed"><code>{key}</code></div>}</Modal>; }
function OAuthDialog({ mode, close, reload, notify }: any) { const [name, setName] = useState(""); const [login, setLogin] = useState<any>(null); const [callback, setCallback] = useState(""); const start = async () => { const popup = window.open("about:blank", "codexOAuthLogin"); if (popup) popup.opener = null; try { const data = await api<any>(`/admin/api/oauth/${mode}/start`, { method: "POST", body: JSON.stringify({ name: name.trim() }) }); setLogin(data.login); if (popup) popup.location.href = mode === "device" ? data.login.verificationUrl : data.login.authorizationUrl; } catch (error) { popup?.close(); notify("无法开始登录", message(error), true); } }; useEffect(() => { if (mode !== "device" || !login) return; const timer = setInterval(async () => { try { const data = await api<any>(`/admin/api/oauth/device/${encodeURIComponent(login.id)}`, { method: "POST", body: "{}" }); if (data.status === "complete") { clearInterval(timer); await reload(); close(); notify("ChatGPT 账户已添加", "认证信息已安全保存并加入轮询。"); } } catch (error) { clearInterval(timer); notify("登录未完成", message(error), true); } }, Math.max(3000, Math.min(30000, (login.intervalSeconds || 5) * 1000))); return () => clearInterval(timer); }, [login]); const cancel = () => { if (login) api(`/admin/api/oauth/${mode}/${encodeURIComponent(login.id)}`, { method: "DELETE" }).catch(() => {}); close(); }; const finish = async () => { try { await api(`/admin/api/oauth/browser/${encodeURIComponent(login.id)}`, { method: "POST", body: JSON.stringify({ callbackUrl: callback.trim() }) }); await reload(); close(); notify("ChatGPT 账户已添加", "回调已验证，认证信息已安全保存。"); } catch (error) { notify("登录未完成", message(error), true); } }; return <Modal title={mode === "device" ? "使用 ChatGPT 添加账户" : "复制链接登录"} subtitle={mode === "device" ? "通过 OpenAI 官方设备码流程登录。" : "兼容 Codex CLI 的 localhost 回调方式。"} close={cancel} footer={!login ? <Button tone="primary" onClick={start}>继续登录</Button> : mode === "browser" ? <Button tone="primary" onClick={finish}>完成导入</Button> : null}>{!login ? <label>显示名称<input value={name} onInput={(e) => setName(e.currentTarget.value)} /></label> : mode === "device" ? <div class="device-code"><span>在 ChatGPT 页面输入一次性代码</span><strong>{login.userCode}</strong><a class="button primary" href={login.verificationUrl} target="_blank" rel="noreferrer">打开 ChatGPT</a></div> : <><p>授权后 localhost 页面可能无法打开，这是正常现象。复制浏览器地址栏中的完整 URL。</p><a class="button" href={login.authorizationUrl} target="_blank" rel="noreferrer">重新打开授权页面</a><label>回调 URL<textarea value={callback} onInput={(e) => setCallback(e.currentTarget.value)} placeholder="http://localhost:1455/auth/callback?code=...&state=..." /></label></>}</Modal>; }

const message = (error: unknown) => error instanceof Error ? error.message : "请求失败";
const tokens = (value?: number) => !value ? "未知" : value >= 1_000_000 ? `${value / 1_000_000}M` : value >= 1000 ? `${Math.round(value / 1000)}K` : String(value);
render(<App />, document.getElementById("app")!);
