name = "codex-oauth-proxy-core"
main = "build/worker.mjs"
compatibility_date = "2025-08-01"
compatibility_flags = [
    "streams_enable_constructors"
]

[vars]
ENV = "production"
DISABLE_HEALTH_LOGS = "true"


[build]
command = "go run github.com/syumai/workers/cmd/workers-assets-gen -mode=go && GOOS=js GOARCH=wasm go build -o ./build/app.wasm cmd/codex-oauth-proxy-worker/main.go"

[observability.logs]
enabled = true
head_sampling_rate = 0.1
invocation_logs = true
persist = true
