import { createUpstreamBinding, EgressEnv } from "./egress";

interface CoreWorker {
  fetch(request: Request, env: Record<string, unknown>, ctx: ExecutionContext): Promise<Response>;
}

interface EmbeddedCoreEnv extends EgressEnv {
  KEY_ENCRYPTION_SECRET: string;
}

let coreWorkerPromise: Promise<CoreWorker> | undefined;

async function loadCoreWorker(): Promise<CoreWorker> {
  if (!coreWorkerPromise) {
    // Generated by workers-assets-gen before the Worker is built.
    // @ts-expect-error The generated JavaScript module has no declaration file.
    coreWorkerPromise = import("../../build/worker.mjs").then((module) => module.default as CoreWorker);
  }
  return coreWorkerPromise;
}

export async function fetchEmbeddedCore(
  request: Request,
  env: EmbeddedCoreEnv,
  ctx: ExecutionContext,
): Promise<Response> {
  const core = await loadCoreWorker();
  return core.fetch(request, {
    ...env,
    INTERNAL_PROXY_KEY: env.KEY_ENCRYPTION_SECRET,
    EGRESS: createUpstreamBinding(env),
  }, ctx);
}
