import { createUpstreamBinding, EgressEnv } from "./egress";

interface CoreWorker {
  fetch(request: Request, env: Record<string, unknown>, ctx: ExecutionContext): Promise<Response>;
}

let coreWorkerPromise: Promise<CoreWorker> | undefined;

async function loadCoreWorker(): Promise<CoreWorker> {
  if (!coreWorkerPromise) {
    // Generated by workers-assets-gen before the Worker is built.
    // @ts-expect-error The generated JavaScript module has no declaration file.
    coreWorkerPromise = import("../../build/worker.mjs").then((module) => module.default as CoreWorker);
  }
  return coreWorkerPromise;
}

export async function fetchEmbeddedCore(
  request: Request,
  env: EgressEnv,
  ctx: ExecutionContext,
): Promise<Response> {
  const core = await loadCoreWorker();
  return core.fetch(request, { ...env, EGRESS: createUpstreamBinding(env) }, ctx);
}
