export const ADMIN_HTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Codex Account Pool</title><style>
:root{color-scheme:dark;--bg:#09111f;--panel:#101c30;--line:#263650;--text:#ecf3ff;--muted:#9babc2;--accent:#64d8b4;--danger:#ff8291}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#162744,var(--bg) 42%);color:var(--text);font:15px/1.5 ui-sans-serif,system-ui;min-height:100vh}main{max-width:980px;margin:auto;padding:48px 20px}h1{font-size:clamp(28px,5vw,48px);margin:0 0 8px}.sub{color:var(--muted);margin-bottom:28px}.card{background:color-mix(in srgb,var(--panel) 92%,transparent);border:1px solid var(--line);border-radius:18px;padding:20px;margin:16px 0;box-shadow:0 18px 60px #0004}.row{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.grow{flex:1}.account{display:grid;grid-template-columns:1fr auto;gap:12px;padding:15px 0;border-bottom:1px solid var(--line)}.account:last-child{border:0}.name{font-weight:700}.meta{font-size:13px;color:var(--muted)}input,textarea,button{font:inherit;border-radius:10px;border:1px solid var(--line);padding:10px 12px;background:#0a1425;color:var(--text)}input,textarea{width:100%}textarea{min-height:160px;font-family:ui-monospace,monospace;font-size:12px}button{cursor:pointer;background:#17304c}button.primary{background:var(--accent);color:#05251d;border:0;font-weight:800}button.danger{color:var(--danger)}button:disabled{opacity:.45;cursor:not-allowed}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.hidden{display:none}.pill{display:inline-block;border-radius:999px;padding:2px 8px;background:#203552;font-size:12px}.ok{color:var(--accent)}.bad{color:var(--danger)}#message{min-height:24px;color:var(--muted)}@media(max-width:650px){.grid{grid-template-columns:1fr}.account{grid-template-columns:1fr}}
</style></head><body><main><h1>Codex account pool</h1><div class="sub">Strongly coordinated multi-account routing on Cloudflare Durable Objects.</div>
<section id="login" class="card"><h2>Admin login</h2><div class="row"><div class="grow"><input id="key" type="password" autocomplete="current-password" placeholder="Admin API key"></div><button class="primary" onclick="login()">Sign in</button></div></section>
<div id="app" class="hidden"><section class="card"><div class="row"><h2 class="grow">Accounts</h2><button onclick="loadAccounts()">Refresh</button><button onclick="logout()">Sign out</button></div><div id="accounts"></div></section>
<section class="card"><h2>Proxy API key</h2><p class="meta">Generate or rotate the client key. It is shown once; only its hash is stored.</p><div class="row"><button class="primary" onclick="generateProxyKey()">Generate / rotate</button><code id="proxyKey" class="grow"></code></div></section>
<section class="card"><h2>Import account</h2><p class="meta">Paste a Codex auth.json, legacy Cloudflare credential JSON, or a flat credential object. Stored tokens are never returned by the API.</p><div class="grid"><input id="name" placeholder="Friendly name (optional)"><span></span></div><textarea id="payload" spellcheck="false" placeholder='{"tokens":{"access_token":"...","refresh_token":"...","account_id":"...","expiresAt":0}}'></textarea><div class="row"><button class="primary" onclick="addAccount()">Import securely</button><span id="message"></span></div></section></div>
</main><script>
const $=id=>document.getElementById(id);async function request(path,options={}){const r=await fetch(path,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});const body=await r.json().catch(()=>({error:'Request failed'}));if(!r.ok)throw new Error(body.error||'Request failed');return body}async function login(){try{await request('/admin/api/session',{method:'POST',body:JSON.stringify({key:$('key').value})});$('key').value='';showApp()}catch(e){$('message').textContent=e.message}}async function logout(){await request('/admin/api/session',{method:'DELETE'});location.reload()}async function showApp(){$('login').classList.add('hidden');$('app').classList.remove('hidden');await loadAccounts()}async function loadAccounts(){try{const data=await request('/admin/api/accounts');$('accounts').innerHTML=data.accounts.length?data.accounts.map(a=>{const cooling=a.cooldownUntil>Date.now();return '<div class="account"><div><div class="name">'+escapeHtml(a.name)+' <span class="pill '+(a.enabled&&!cooling?'ok':'bad')+'">'+(a.enabled?(cooling?'cooldown':'enabled'):'disabled')+'</span></div><div class="meta">Account '+escapeHtml(a.accountId)+' · expires '+new Date(a.expiresAt).toLocaleString()+' · failures '+a.failureCount+'</div></div><div class="row"><button onclick="toggleAccount(\\''+a.id+'\\','+!a.enabled+')">'+(a.enabled?'Disable':'Enable')+'</button><button class="danger" onclick="removeAccount(\\''+a.id+'\\')">Remove</button></div></div>'}).join(''):'<p class="meta">No accounts configured.</p>'}catch(e){if(e.message==='Unauthorized')location.reload();else $('message').textContent=e.message}}async function addAccount(){try{const parsed=JSON.parse($('payload').value);if($('name').value)parsed.name=$('name').value;await request('/admin/api/accounts',{method:'POST',body:JSON.stringify(parsed)});$('payload').value='';$('name').value='';$('message').textContent='Account imported';await loadAccounts()}catch(e){$('message').textContent=e.message}}async function generateProxyKey(){if(!confirm('Rotate the proxy API key? Existing clients will stop working.'))return;const data=await request('/admin/api/proxy-key',{method:'POST',body:'{}'});$('proxyKey').textContent=data.key}async function toggleAccount(id,enabled){await request('/admin/api/accounts/'+id,{method:'PATCH',body:JSON.stringify({enabled})});await loadAccounts()}async function removeAccount(id){if(!confirm('Remove this account?'))return;await request('/admin/api/accounts/'+id,{method:'DELETE'});await loadAccounts()}function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}fetch('/admin/api/accounts').then(r=>{if(r.ok)showApp()});
</script></body></html>`;
